### ISSUE TITLE
any plans to compile custom kernel for 6.10 RC？

### ISSUE THREAD

**Issue by Always67** [thor2002ro/unraid_kernel#2]
Could you please compile the 6.10rc5 kernel? I am using a Jasper Lake processor. I have to enable GUC/HUC to use hardware acceleration. But the GUC/HUC was confirmed to be completely broken on the 5.15 kernel used by 6.10RC. Unfortunately, it's only possible to use the 5.16 kernel until 6.11RC. I used your kernel in 6.10RC5 and the GUC/HUC is perfectly fine. But got array stopped • incompatible md version error. I know it's because of the wrong version of unraid. I don't know how to compile kernels, so would like to ask for your help.

**Comment by thor2002ro** [comment]
in the last version you can use 
UNRAID: param overwrite unraid driver patch level
append to kernel cmdline md_mod.unraid_patch=nr 

	  13 for unraid 6.8.3,
	  17 for unraid 6.9.2,
	  18 for unraid 6.10rc1,
	  19 for unraid 6.10rc2,
	  21 for unraid 6.10rc3,
	  22 for unraid 6.10rc4/6.10rc5,
	  etc....
add md_mod.unraid_patch=22 in the cmdline of the kernel..... and will work since there's no real difference between these versions just kernel version adaptations....

**Comment by flyize** [comment]
Any way to include bzfirmware for this version?

**Comment by Always67** [comment]
My server keeps rebooting with the xxx-zen-xxxx.7z version when loading bzboot
the CPU is N6005
But the good news is I have tried a patch made by ich777 so that the GUC/huc works well on the official kernel
