### ISSUE TITLE
How to install this

### ISSUE THREAD

**Issue by ksullivan86** [thor2002ro/unraid_kernel#24]
I would like to use your unraid kernel but I am not super clear on the instructions as there isn't any "install" info in the readme. From what I have gathered from reddit is the process is a simple replace current files onto the unraid flash boot.

Also I read that if done correctly this shouldn't change anything for the next upgrade process as in I shouldn't have to put the original files back in order to upgrade... Is this true?

I have the newest unraid 6.12.8 installed, from other post it seems only some will work with 6.12.8. I am guessing all the ones 6.12.8 tag will work but is there one you recommend? I guessing just the one with the "latest" tag?

the reason I want to use the newer kernel is intel arc 
also any idea if the aspm low under 1 watt idle is possible with your kernel?
Thanks for being ahead of unraid in their kernel development!

**Comment by kaaresgut** [comment]
The easy way is to get kernel 6.7.0 for 6.12.8. There are four files in there. just copy those over to the usb-drive. It should overwrite four of the files already there. I would keep a backup of the originals on the usb as well just in case.

The reason you want kernel 6.7.0 is because later ones need other changes to unraid as well to keep network working. Not too tricky, but if arc support is all you want then just try 6.7.0. No need to bother with the extras folder either unless you know you need it.

The new kernel shouldn't have any impact on upgrading unraid later. The unraid upgrade process will just overwrite these files with new originals.

**Comment by ksullivan86** [comment]
> The reason you want kernel 6.7.0 is because later ones need other changes to unraid as well to keep network working. Not too tricky, but if arc support is all you want then just try 6.7.0. No need to bother with the extras folder either unless you know you need it.

ok thanks I will grab 6.7.0. Is there somewhere you are getting the info? how do you know about the extra folders?

**Comment by afritsch89** [comment]
im on 6.12.10 is 6.9.5 20240619 o2 gcc 6.12.9/6.12.10 #2 just as easy to install?
what are the other changes you speak of?

> The easy way is to get kernel 6.7.0 for 6.12.8. There are four files in there. just copy those over to the usb-drive. It should overwrite four of the files already there. I would keep a backup of the originals on the usb as well just in case.
> 
> The reason you want kernel 6.7.0 is because later ones need other changes to unraid as well to keep network working. Not too tricky, but if arc support is all you want then just try 6.7.0. No need to bother with the extras folder either unless you know you need it.
> 
> The new kernel shouldn't have any impact on upgrading unraid later. The unraid upgrade process will just overwrite these files with new originals.

im on 6.12.10 is 6.9.5 20240619 o2 gcc 6.12.9/6.12.10 #2 just as easy to install?
what are the other changes you speak of?

**Comment by kaaresgut** [comment]
It should be just as easy. Just copy the four files over. Make sure you keep a backup of the originals in case you need to roll back.
No changes needed, that was a fix for some older kernels.
