### ISSUE TITLE
an update based on 6.12, please

### ISSUE THREAD

**Issue by viogus** [thor2002ro/unraid_kernel#8]
unraid 6.12 is out and it is awesome.

**Comment by thor2002ro** [comment]
I will get to it as some point... but not while its RC....

**Comment by jaimbo** [comment]
Hey @thor2002ro, now that Unraid 6.12 has left RC, are you planning on building Kernel 6.2? (I think this is the latest with ZFS support?)

Would love to be able to use my Intel Arc card for hardware transcoding :)

**Comment by thor2002ro** [comment]
I will update it soon... But at the moment I've seen only issues with 6.12.... Don't quite want to deal will it at the moment since my server is rock solid with 6.11.5 and my kernel....

And also they messed with the file structure the modules file contains some unraid files(stupid aproch if you ask me.... They could've made their own file to load and not mess with the standard Linux modules file) now need to take a diffrent aproch to loading external modules since I don't want to mess up the update process

**Comment by jaimbo** [comment]
Sounds good! Happy to help with testing if needed as well :)
